id: P003029
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 10:35:17.270832
source_metadata:
  id: bdr:W2CZ8050
  title: ཕར་ཕྱིན་སྐབས་བརྒྱད་ཀྱི་དྲི་བ་དྲིས་ལན་ཐོས་བསམ་བློ་ཡི་རོལ་རྩེད།
  author: ''
  volumes:
    fc6f2dff81c34143b138262799dd9c61:
      image_group_id: I1KG10324
      title: ''
      volume_number: 1
      total_pages: 974
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
